Repository Team-Ilmansa/yeogiga-web, pull requests merged in 2025-08, with the labels that each got.

#91 Feature(IL-229): 마이페이지 내 사용자 정보 UI 구현
  package-lock.json
  package.json
  src/components/home/HomeButton.jsx
  src/components/mypage/FavoritePhotos.jsx
  src/components/mypage/PastTrip.jsx
  src/components/mypage/ProfileCard.jsx
  src/pages/Home.jsx
  src/pages/MyPage.jsx
Labels: chore, feat, User 👤, UI 👀

#94 Feature(IL-235): 마이페이지 하단 부가 기능 UI
  src/components/mypage/AccountSettings.jsx
  src/pages/MyPage.jsx
Labels: feat, User 👤, UI 👀

#93 Feature(IL-234): 여행 참가 페이지 UI 리디자인
  src/assets/dashboard/modal/LocationIcon.jsx
  src/pages/Participation.jsx
Labels: feat, User 👤, UI 👀

#96 Feature(IL-238): 공지사항 생성 API 연동
  src/App.jsx
  src/apis/notice/createNoticeApi.jsx
  src/components/notice/CreateNotices.jsx
  src/components/notice/Notices.jsx
Labels: feat, Trip🚗, Notice‼️

#97 Feature(IL-239): 공지사항 삭제 API 연동 구현
  src/apis/notice/deleteNoticeApi.jsx
  src/components/notice/Notices.jsx
Labels: feat, Trip🚗, Notice‼️

#98 Feature(IL-242): 네이버 지도 API 연결
  .github/workflows/cd.yml
  index.html
  src/App.jsx
  src/components/dashboard/schedule/DateBox.jsx
  src/pages/PlaceMap.jsx
Labels: feat

#99 Feature(IL-240): 특정 공지사항 조회 API 연동 구현
  src/App.jsx
  src/apis/notice/readSpecificNoticeApi.jsx
  src/components/notice/Notices.jsx
  src/components/notice/PastNotices.jsx
Labels: feat, Trip🚗, UI 👀, Notice‼️

#100 Feature(IL-244): 공지사항 수정 API 연동 구현
  src/apis/notice/updateNoticeApi.jsx
  src/components/notice/PastNotices.jsx
Labels: feat, Trip🚗, Notice‼️

#104 Feature(IL-253): 특정 일자에 장소 추가
  src/App.jsx
  src/apis/map/addPlaceApi.jsx
  src/components/dashboard/schedule/DateBox.jsx
  src/components/dashboard/schedule/DayTabs.jsx
  src/pages/PlaceMap.jsx
Labels: feat, Map 🗺️

#106 Feature(IL-255): 계정 복구 API 연동
  src/App.jsx
  src/apis/authentication/oauthSignInApi.jsx
  src/apis/authentication/regularSignInApi.jsx
  src/apis/authentication/restoreAccountApi.jsx
  src/components/sign-in/KakaoRedirect.jsx
  src/components/sign-in/NaverRedirect.jsx
  src/components/sign-in/SignInForm.jsx
  src/pages/RestoreAccount.jsx
Labels: feat, Authentication 🔒, User 👤

#108 Feature(IL-206): 대시보드 내 일자별 임시 저장 목적지 조회
  src/apis/dashboard/readDatePlaceApi.jsx
  src/assets/dashboard/ArrowDown.jsx
  src/assets/dashboard/ArrowUp.jsx
  src/assets/dashboard/CalendarIcon.jsx
  src/assets/dashboard/ImageUploadIcon.jsx
  src/assets/dashboard/KebabIcon.jsx
  src/assets/dashboard/NoUploadImage.jsx
  src/assets/dashboard/PinIcon.jsx
  src/assets/dashboard/PlaceIcon.jsx
  src/assets/dashboard/UserIcon.jsx
  src/components/dashboard/schedule/DateBox.jsx
Labels: feat, Trip🚗

#107 Fix(IL-256): trip api status 추가
  src/apis/trip/readTripApi.jsx
Labels: fix, Authentication 🔒, Trip🚗

#109 Feature(IL-257): 마이페이지 소셜로그인 플랫폼 별 로고 표시
  src/assets/mypage/kakaoIcon.png
  src/assets/mypage/naverIcon.png
  src/components/mypage/ProfileCard.jsx
  src/components/sign-in/KakaoRedirect.jsx
  src/components/sign-in/NaverRedirect.jsx
Labels: feat, User 👤, UI 👀

#111 Feature(IL-259): 임시 저장 장소 삭제(컨텍스트 메뉴) 구현
  src/apis/dashboard/deleteDatePlaceApi.jsx
  src/components/dashboard/schedule/DateBox.jsx
  src/components/dashboard/schedule/SortablePlaceItem.jsx
Labels: feat, Trip🚗

#113 Feature(IL-260): 일자별 장소 순서 추천
  src/apis/dashboard/recommendDatePlaceOrderApi.jsx
  src/components/dashboard/schedule/DateBox.jsx
Labels: feat, Trip🚗

#114 Fix(IL-215): 일정 확정 시 이동 경로 수정
  src/components/trip/TripConfirmCalendar.jsx
Labels: fix, Calendar 🗓️

#115 Feature(IL-261): 여행 일정 확정 기능 구현
  src/apis/dashboard/confirmTripPlaceApi.jsx
  src/components/dashboard/schedule/DateBox.jsx
  src/components/dashboard/schedule/DayTabs.jsx
  src/components/dashboard/schedule/ScheduleDashBoard.jsx
Labels: feat, Trip🚗, UI 👀

#116 Fix(IL-205): 여행 상태별 조건부 렌더링 오타 수정
  src/components/dashboard/TripTitle.jsx
Labels: fix, Trip🚗, UI 👀

#118 Feature(IL-264): 대시보드 하단 버튼 UI 구현
  src/assets/dashboard/NoticeIcon.jsx
  src/components/dashboard/schedule/DateBox.jsx
  src/components/dashboard/schedule/DayTabs.jsx
Labels: feat, Trip🚗, UI 👀

#122 Fix(IL-271): 게스트 회원 등록 페이지 UI 오류 수정
  src/components/sign-up/GuestSignUp.jsx
  src/components/sign-up/SignUpForm.jsx
  src/components/sign-up/StepIndicator.jsx
Labels: fix, UI 👀

#124 Feature(IL-276): API 기본 요청 주소 변경
  .github/workflows/cd.yml
  src/apis/authentication/oauthSignInApi.jsx
  src/apis/authentication/reissueAccessTokenApi.jsx
  src/apis/authentication/signOutApi.jsx
  src/apis/dashboard/confirmTripPlaceApi.jsx
  src/apis/map/addPlaceApi.jsx
  src/apis/map/addPlanningPlaceApi.jsx
  src/apis/map/searchPlaceApi.jsx
  src/apis/notice/readSpecificNoticeApi.jsx
  src/apis/notice/updateNoticeApi.jsx
  src/apis/planning-dashboard/readPlanningDatePlaceApi.jsx
  src/apis/trip/readMainApi.jsx
  src/apis/trip/updateTripTimeApi.jsx
  src/components/sign-in/KakaoRedirect.jsx
  src/config/Env.jsx
Labels: feat

#125 Feature(IL-277): 일정 확정후 여행 API 연결
  src/components/dashboard/schedule/DayTabs.jsx
  src/components/dashboard/schedule/PlanningDateBox.jsx
Labels: feat, Trip🚗, Map 🗺️

#127 Feature(IL-272): 계정 복구 UI 구현
  src/components/common/FixedActionBar.jsx
  src/components/dashboard/schedule/DayTabs.jsx
  src/components/sign-in/SignInForm.jsx
  src/pages/RestoreAccount.jsx
Labels: feat, User 👤, UI 👀
