Repository Team-Ilmansa/yeogiga-web, pull requests merged in 2025-09, with the labels that each got.

#131 Feature(IL-289): 이미지 임시 업로드
  src/apis/image/uploadImagesApi.jsx
  src/components/dashboard/SlideTabs.jsx
  src/components/dashboard/galary/GalaryDashboard.jsx
  src/components/dashboard/gallery/DayTabs.jsx
  src/components/dashboard/gallery/GalleryDashboard.jsx
  src/components/dashboard/gallery/PhotoAlbum.jsx
Labels: feat, refact

#138 Feature(IL-301): 사진 확대 보기 UI 구현
  src/components/dashboard/gallery/PhotoAlbum.jsx
Labels: feat, UI 👀, Image 📸

#143 Feature(IL-325): 메인화면 내 날씨 UI
  src/apis/home/getWeatherApi.jsx
  src/assets/home/weather/ClearBackground.png
  src/assets/home/weather/ClearIcon.jsx
  src/assets/home/weather/CloudBackground.png
  src/assets/home/weather/CloudIcon.jsx
  src/assets/home/weather/RainBackground.png
  src/assets/home/weather/RainIcon.jsx
  src/assets/home/weather/SnowBackground.png
  src/assets/home/weather/SnowIcon.jsx
  src/assets/home/weather/WindBackground.png
  src/assets/home/weather/WindIcon.jsx
  src/components/home/HomeTitle.jsx
  src/components/home/PastTrips.jsx
  src/components/home/RecommendedPlaces.jsx
  src/components/home/TrendingPlaces.jsx
  src/components/home/utils/PlannedTripSlide.jsx
  src/config/Env.jsx
  src/pages/Home.jsx
Labels: feat, UI 👀

#145 Fix(IL-325): 날씨 API URL 환경 변수 적용
  .github/workflows/cd.yml
  src/apis/home/getWeatherApi.jsx
  src/config/Env.jsx
Labels: fix, UI 👀

#146 Feature(IL-323): 정산 내역 UI 수정 및 API 연동
  src/App.jsx
  src/apis/member/readMemberApi.jsx
  src/apis/settlement/createSettlementApi.jsx
  src/components/common/CategorySelector.jsx
  src/pages/AccountAdd.jsx
  src/pages/Dashboard.jsx
  src/pages/SettlementAdd.jsx
  src/pages/SettlementBook.jsx
Labels: docs, feat, UI 👀, Account book🧾

#147 Feature(IL-325): 날씨 API 백엔드 서버로 변경
  .github/workflows/cd.yml
  src/apis/home/getWeatherApi.jsx
  src/components/home/HomeTitle.jsx
Labels: feat, fix, UI 👀

#149 Feature(IL-327): 정산 내역 전체 조회 API 연동 및 페이지 구현
  src/App.jsx
  src/apis/settlement/readTotalSettlementsApi.jsx
  src/assets/settlement/PigIcon.jsx
  src/assets/settlement/UserIcon.jsx
  src/components/settlement/SettlementBox.jsx
  src/components/settlement/SettlementTabs.jsx
  src/components/settlement/UnsettledTitle.jsx
  src/pages/Dashboard.jsx
  src/pages/SettlementAdd.jsx
  src/pages/SettlementBook.jsx
Labels: feat, refact, UI 👀, Account book🧾
