Repository Team-Ilmansa/yeogiga-web, pull requests merged in 2025-05, with the labels that each got.

#6 Docs: PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs

#8 Chore(IL-64): Prettier, ESLint 설정
  .prettierrc
  eslint.config.js
  package-lock.json
  package.json
  src/App.jsx
  src/index.css
Labels: chore

#10 Feature(IL-63): 절대 경로 설정
  jsconfig.json
  src/components/Component.jsx
  vite.config.js
Labels: feat

#11 Feature(IL-65): meta 태그 추가
  index.html
Labels: feat

#12 Feature(IL-67): 라우팅 기본 설정
  package-lock.json
  package.json
  src/App.jsx
  src/components/Component.jsx
  src/components/login/LoginForm.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  vite.config.js
Labels: feat

#13 Feature(IL-75): 회원가입
  .prettierrc
  jsconfig.json
  package-lock.json
  package.json
  src/App.jsx
  src/apis/api.jsx
  src/apis/authentication/signUpApi.jsx
  src/components/login/LoginForm.jsx
  src/components/sign-up/SignUpForm.jsx
  src/index.css
  src/pages/SignUp.jsx
Labels: feat

#14 Refact(IL-76): 일반 로그인 파일명 및 컴포넌트명 변경
  src/App.jsx
  src/components/sign-in/SignInForm.jsx
  src/pages/Login.jsx
  src/pages/SignIn.jsx
Labels: refact

#15 Feature(IL-78): 일반로그인 API 구현
  src/apis/authentication/regularSignInApi.jsx
Labels: feat

#16 Feature(IL-76): 일반 로그인 UI 구현 및 API 연결
  src/components/sign-in/SignInForm.jsx
  src/pages/Home.jsx
Labels: feat

#17 Feature(IL-72): OAuth 로그인 API 호출 및 카카오 로그인 연동
  .gitignore
  src/App.jsx
  src/apis/api.jsx
  src/apis/authentication/oauthSignInApi.jsx
  src/assets/kakaoButton.png
  src/components/sign-in/KakaoRedirect.jsx
  src/components/sign-in/SignInButton.jsx
  src/components/sign-in/SignInForm.jsx
  src/config/Env.jsx
  src/config/Url.jsx
  src/main.jsx
Labels: feat

#19 Feature(IL-91): 환경 변수 설정
  .github/workflows/cd.yml
  .gitignore
  src/apis/authentication/regularSignInApi.jsx
  src/apis/authentication/signUpApi.jsx
Labels: feat

#20 Fix(IL-91): 환경 변수 적용 코드 수정
  .github/workflows/cd.yml
Labels: fix

#22 Fix(IL-91): 환경 변수 workflow 수정
  .github/workflows/cd.yml
Labels: fix

#23 Feature(IL-93): Context API 적용
  src/App.jsx
  src/apis/api.jsx
  src/components/sign-in/KakaoRedirect.jsx
  src/components/sign-in/NaverRedirect.jsx
  src/components/sign-in/SignInForm.jsx
  src/contexts/AuthContext.jsx
  src/contexts/AuthProvider.jsx
  src/contexts/AuthUtil.jsx
  src/hooks/useAuth.jsx
  src/main.jsx
Labels: feat, Authentication 🔒

#24 Feature(IL-98): 아이디 및 닉네임 중복 확인 구현
  src/apis/authentication/nicknameDupCheck.jsx
  src/apis/authentication/usernameDupCheck.jsx
  src/components/sign-up/SignUpForm.jsx
Labels: feat, Authentication 🔒

#25 Feature(IL-90): 로그아웃 구현
  src/apis/authentication/signOutApi.jsx
  src/contexts/AuthProvider.jsx
  src/pages/Home.jsx
Labels: feat, Authentication 🔒

#26 Feature(IL-101): 마이페이지 회원 정보 조회
  src/App.jsx
  src/apis/api.jsx
  src/apis/users/userInfoApi.jsx
  src/index.css
  src/pages/Home.jsx
  src/pages/MyPage.jsx
Labels: feat, User 👤

#27 Feature(IL-108): 닉네임 변경
  src/apis/users/updateNicknameApi.jsx
  src/pages/MyPage.jsx
Labels: feat, User 👤

#29 Feature(IL-110): 비밀번호 변경 API
  src/apis/users/patchUsersPasswordApi.jsx
  src/pages/MyPage.jsx
Labels: feat, User 👤

#30 Feature(IL-118): 여행 생성
  src/apis/trip/createTripApi.jsx
  src/pages/Home.jsx
Labels: feat, Trip🚗

#31 Refact(IL-128): 코드 리팩토링
  src/apis/api.jsx
  src/apis/authentication/nicknameDupCheckApi.jsx
  src/apis/authentication/regularSignInApi.jsx
  src/apis/authentication/reissueAccessTokenApi.jsx
  src/apis/authentication/usernameDupCheckApi.jsx
  src/apis/users/updatePasswordApi.jsx
  src/components/sign-in/KakaoRedirect.jsx
  src/components/sign-in/NaverRedirect.jsx
  src/components/sign-in/SignInButton.jsx
  src/components/sign-in/SignInForm.jsx
  src/components/sign-up/SignUpForm.jsx
  src/hooks/useAuth.jsx
  src/pages/Home.jsx
  src/pages/MyPage.jsx
Labels: refact

#33 Feature(IL-144): 로그인타입에 따른 UI 컴포넌트 조건부 렌더링
  src/contexts/AuthProvider.jsx
  src/contexts/AuthUtil.jsx
  src/pages/MyPage.jsx
Labels: feat, Authentication 🔒, User 👤

#34 Fix(IL-149): 닉네임 변경 시 로그아웃 처리
  src/pages/MyPage.jsx
Labels: feat, Authentication 🔒, User 👤

#35 Feature(IL-150): 메인 화면 내 여행 조회 API 연동
  src/apis/trip/readMainApi.jsx
  src/pages/Home.jsx
Labels: feat, Trip🚗
