Repository Team-Ilmansa/yeogiga-web, pull requests merged in 2025-07, with the labels that each got.

#53 Feature(IL-186): 멤버 더 보기 화면 구현
  src/components/trip/TripInfo.jsx
Labels: feat, User 👤, Trip🚗

#54 Feature(IL-189): 웹앱 UI 적용 테스트
  src/App.jsx
  src/assets/sign-in/kakaoLogo.png
  src/assets/sign-in/logo.png
  src/assets/sign-in/naverLogo.png
  src/components/sign-in/SignInButton.jsx
  src/components/sign-in/SignInForm.jsx
  src/pages/Home.jsx
  src/pages/SignIn.jsx
Labels: feat, UI 👀

#57 Feature(IL-192): 여행 멤버 추방 API 연동
  src/apis/member/deleteTripMemberApi.jsx
  src/components/trip/TripInfo.jsx
Labels: feat, Trip🚗

#56 Feature(IL-191): 여행 탈퇴 API 연동
  src/apis/member/deleteMemberApi.jsx
  src/components/trip/TripInfo.jsx
Labels: feat, Trip🚗

#59 Feature(IL-189): 색상 변수 설정 및 적용
  src/App.jsx
  src/components/sign-in/SignInForm.jsx
  src/index.css
  src/pages/SignIn.jsx
Labels: feat, UI 👀

#63 Feature(IL-200): 메인화면 하단바 버튼 기능 추가 및 UI 조정
  src/assets/home/HomeIcon.jsx
  src/assets/home/MyPageIcon.jsx
  src/components/home/HomeButton.jsx
Labels: feat, UI 👀

#65 Feature(IL-201): 회원가입 화면 - 이메일 인증 화면 UI 구현
  src/assets/sign-up/GoBack.jsx
  src/components/sign-up/PrevSignUpForm.jsx
  src/components/sign-up/RegisterEmail.jsx
  src/components/sign-up/SignUpForm.jsx
  src/components/sign-up/StepIndicator.jsx
  src/pages/SignUp.jsx
Labels: feat, UI 👀

#68 Feature(IL-184): 회원가입 이메일 인증 기능 구현
  src/apis/authentication/emailRequestApi.jsx
  src/apis/authentication/verifyCodeApi.jsx
  src/components/sign-up/RegisterEmail.jsx
  src/components/sign-up/SignUpForm.jsx
Labels: feat, User 👤, UI 👀

#69 Feature(IL-195): 여행 대시보드 타이틀 및 특정 여행 조회 API 연동
  src/App.jsx
  src/assets/dashboard/CalendarIcon.jsx
  src/assets/dashboard/PinIcon.jsx
  src/assets/dashboard/UserIcon.jsx
  src/components/dashboard/TripTitle.jsx
  src/components/trip/TripCalendar.jsx
  src/pages/Dashboard.jsx
Labels: Trip🚗, UI 👀

#70 Feature(IL-184): 회원가입 2단계 - 아이디, 비밀번호 등록
  src/assets/sign-up/Check.jsx
  src/components/sign-up/RegisterPassword.jsx
  src/components/sign-up/SignUpForm.jsx
Labels: feat, User 👤, UI 👀

#71 Feature(IL-184): 회원가입 단계 4 - 닉네임 등록
  src/components/sign-up/RegisterNickname.jsx
  src/components/sign-up/SignUpForm.jsx
Labels: feat, User 👤

#75 Feature(IL-206): 일정 대시보드 UI 및 구조 개선, 탭 기능 통합
  src/components/dashboard/SlideTabs.jsx
  src/components/dashboard/TripTitle.jsx
  src/components/dashboard/schedule/DateBox.jsx
  src/components/dashboard/schedule/DayTabs.jsx
  src/components/dashboard/schedule/ScheduleDashBoard.jsx
  src/pages/Dashboard.jsx
Labels: feat, refact, Trip🚗, UI 👀

#76 Refact(IL-207): 로그인, 회원가입 리팩토링
  src/assets/home/HomeIcon.jsx
  src/assets/home/MyPageIcon.jsx
  src/assets/sign-up/Check.jsx
  src/assets/sign-up/GoBack.jsx
  src/components/sign-in/SignInForm.jsx
  src/components/sign-up/RegisterPassword.jsx
Labels: refact, User 👤

#77 Feature(IL-209): W2M UI 적용 - 최초 날짜 선택 캘린더
  src/components/trip/FirstCalendar.jsx
  src/components/trip/TripCalendar.jsx
  src/pages/Trip.jsx
Labels: feat, Calendar 🗓️, UI 👀

#78 Feature(IL-217): 갤러리 대시보드 일정탭 구현
  src/components/dashboard/SlideTabs.jsx
  src/components/dashboard/galary/DayTabs.jsx
  src/components/dashboard/galary/GalaryDashboard.jsx
Labels: feat, Trip🚗, UI 👀

#80 Feature(IL-219): 여행 일정 확정 전 UI 구현
  src/apis/calendar/readMyCalendarApi.jsx
  src/assets/dashboard/CalendarIcon.jsx
  src/components/dashboard/SlideTabs.jsx
  src/components/dashboard/TripTitle.jsx
  src/components/dashboard/schedule/ScheduleDashBoard.jsx
  src/components/trip/TripCalendar.jsx
  src/pages/Dashboard.jsx
Labels: feat, Calendar 🗓️, UI 👀

#81 Feature(IL-128): 사진 앨범 임시 UI 구현
  src/assets/dashboard/ImageUploadIcon.jsx
  src/assets/dashboard/NoUploadImage.jsx
  src/components/dashboard/galary/GalaryDashboard.jsx
  src/components/dashboard/galary/PhotoAlbum.jsx
Labels: feat, User 👤, UI 👀

#84 Refact(IL-224): 기존 임시 구현 코드 삭제 및 리팩토링
  src/App.jsx
  src/components/trip/FirstCalendar.jsx
  src/components/trip/TripCalendar.css
  src/components/trip/TripCalendar.jsx
  src/components/trip/TripConfirmCalendar.jsx
  src/pages/ConfirmCalendar.jsx
  src/pages/Dashboard.jsx
  src/pages/TripCalendar.jsx
Labels: refact, Calendar 🗓️

#85 Fix(IL-225): 새로고침 시 로그아웃 되는 현상 해결
  src/contexts/AuthProvider.jsx
  src/pages/Home.jsx
Labels: fix, User 👤

#86 Feature(IL-221): 대시보드 내 케밥 버튼 및 모달창 구현
  src/assets/dashboard/KebabIcon.jsx
  src/assets/dashboard/modal/CalendarIcon.jsx
  src/assets/dashboard/modal/EditIcon.jsx
  src/assets/dashboard/modal/RemoveIcon.jsx
  src/assets/dashboard/modal/ShareIcon.jsx
  src/assets/sign-up/GoBack.jsx
  src/components/dashboard/modal/KebobModal.jsx
  src/pages/Dashboard.jsx
Labels: feat, Trip🚗, UI 👀

#87 Feature(IL-226): 모달 기능별 API 연동
  src/components/dashboard/modal/KebabModal.jsx
  src/components/dashboard/modal/KebobModal.jsx
  src/components/dashboard/modal/UpdateTitleModal.jsx
  src/pages/Dashboard.jsx
Labels: feat, Trip🚗, UI 👀

#88 Feature(IL-227): 여행 참가 페이지 UI 수정
  src/pages/Participation.jsx
Labels: feat, User 👤, Trip🚗, UI 👀

#89 Feature(IL-73): 권한 별 라우팅 설정
  src/App.jsx
  src/components/common/ProtectedRoute.jsx
  src/contexts/AuthProvider.jsx
  src/pages/Home.jsx
Labels: feat, Authentication 🔒
